import { Task, MasterItem, ActivityLog, NotificationItem, TaskStatus } from '@/types/dashboard';

export const INITIAL_MASTER_ITEMS: MasterItem[] = [
  // Projects
  { id: 'proj-1', name: 'Q3 Brand Awareness Campaign', category: 'Projects', status: 'Active', description: 'National digital and out-of-home campaign', createdAt: '2026-07-01' },
  { id: 'proj-2', name: 'Product Launch v4.0', category: 'Projects', status: 'Active', description: 'GTM strategy & creative collateral', createdAt: '2026-07-05' },
  { id: 'proj-3', name: 'SEO & Content Overhaul', category: 'Projects', status: 'Active', description: 'Blog and landing page optimization', createdAt: '2026-07-10' },
  { id: 'proj-4', name: 'Annual Customer Conference 2026', category: 'Projects', status: 'Active', description: 'Event marketing & sponsor booth designs', createdAt: '2026-07-12' },
  { id: 'proj-5', name: 'Social Media Growth Hacking', category: 'Projects', status: 'Active', description: 'Short-form video and influencer partnerships', createdAt: '2026-07-15' },

  // Departments
  { id: 'dept-1', name: 'Brand & Creative', category: 'Departments', status: 'Active', description: 'Design, video, branding assets', createdAt: '2026-07-01' },
  { id: 'dept-2', name: 'Performance Marketing', category: 'Departments', status: 'Active', description: 'PPC, Meta Ads, Paid Search', createdAt: '2026-07-01' },
  { id: 'dept-3', name: 'Product Marketing', category: 'Departments', status: 'Active', description: 'Sales enablement, positioning, collateral', createdAt: '2026-07-01' },
  { id: 'dept-4', name: 'Content & PR', category: 'Departments', status: 'Active', description: 'Blog posts, press releases, copy', createdAt: '2026-07-01' },
  { id: 'dept-5', name: 'Event Marketing', category: 'Departments', status: 'Active', description: 'Field events, webinars, conferences', createdAt: '2026-07-01' },

  // Team Members
  { id: 'team-1', name: 'Aarav Sharma', category: 'Team Members', status: 'Active', description: 'Lead Creative Strategist', createdAt: '2026-07-01' },
  { id: 'team-2', name: 'Priya Verma', category: 'Team Members', status: 'Active', description: 'Senior Growth Marketer', createdAt: '2026-07-01' },
  { id: 'team-3', name: 'Rohan Mehta', category: 'Team Members', status: 'Active', description: 'Content Marketing Manager', createdAt: '2026-07-01' },
  { id: 'team-4', name: 'Ananya Gupta', category: 'Team Members', status: 'Active', description: 'Design Director', createdAt: '2026-07-01' },
  { id: 'team-5', name: 'Karan Patel', category: 'Team Members', status: 'Active', description: 'Events Coordinator', createdAt: '2026-07-01' },

  // Agencies
  { id: 'agency-1', name: 'Apex Creative Studio', category: 'Agencies', status: 'Active', description: 'Full-service digital creative agency', createdAt: '2026-07-01' },
  { id: 'agency-2', name: 'Apex Media Global', category: 'Agencies', status: 'Active', description: 'Performance media buying partner', createdAt: '2026-07-01' },
  { id: 'agency-3', name: 'Echo PR Studio', category: 'Agencies', status: 'Active', description: 'Public relations and communications', createdAt: '2026-07-01' },
  { id: 'agency-4', name: 'PixelPerfect Visuals', category: 'Agencies', status: 'Active', description: 'Video production & 3D motion graphics', createdAt: '2026-07-01' },

  // Vendors
  { id: 'vendor-1', name: 'PrintCraft Solutions', category: 'Vendors', status: 'Active', description: 'Large format printing and merchandise', createdAt: '2026-07-01' },
  { id: 'vendor-2', name: 'CloudScale Hosting', category: 'Vendors', status: 'Active', description: 'CDN and landing page infrastructure', createdAt: '2026-07-01' },
  { id: 'vendor-3', name: 'OmniStream Video', category: 'Vendors', status: 'Active', description: 'Livestreaming equipment rental', createdAt: '2026-07-01' },
  { id: 'vendor-4', name: 'EventPro Logistics', category: 'Vendors', status: 'Active', description: 'Booth shipping & booth construction', createdAt: '2026-07-01' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'TSK-1001',
    project: 'Q3 Brand Awareness Campaign',
    taskName: 'Hero Billboard Video Commercial Production',
    taskBrief: 'Create a 30-second high-impact anamorphic 3D video commercial for Times Square and digital displays.',
    department: 'Brand & Creative',
    internalPoc: 'Ananya Gupta',
    agency: 'Apex Creative Studio',
    vendor: 'PixelPerfect Visuals',
    priority: 'Urgent',
    taskProgress: 'In Progress',
    deadline: '2026-08-10',
    executionStarted: true,
    executionStartDate: '2026-07-15',
    actualFinishedDate: null,
    toBeApprovedByManagement: false,
    submittedForApprovalAt: null,
    approvalDate: null,
    remarks: 'Script approved by CMO. Initial 3D renders in review.',
    budget: 25000,
    actualSpend: 18500,
    subtasks: [
      { id: 'st-1', title: 'Scriptwriting & Storyboard Sign-off', completed: true },
      { id: 'st-2', title: '3D Anamorphic Model Render', completed: true },
      { id: 'st-3', title: 'Sound Design & Voiceover Audio', completed: false },
      { id: 'st-4', title: 'Final 4K Resolution Export', completed: false },
    ],
    comments: [
      { id: 'c-1', author: 'Ananya Gupta', role: 'Marketing Team', text: 'Initial 3D render draft sent to CMO for feedback.', timestamp: '2026-07-28T14:20:00Z' },
      { id: 'c-2', author: 'Management Approver', role: 'Management', text: 'Looks promising! Please boost contrast on product logo in frame 4.', timestamp: '2026-07-28T16:00:00Z' }
    ],
    isOverdue: false,
    createdAt: '2026-07-15T09:30:00Z',
    updatedAt: '2026-07-28T14:20:00Z',
  },
  {
    id: 'TSK-1002',
    project: 'Product Launch v4.0',
    taskName: 'GTM Keynote Deck & Launch Video Package',
    taskBrief: 'Design executive presentation slides and produce CEO keynote opening teaser video.',
    department: 'Product Marketing',
    internalPoc: 'Priya Verma',
    agency: 'Apex Creative Studio',
    vendor: 'OmniStream Video',
    priority: 'High',
    taskProgress: 'To Be Approved by Management',
    deadline: '2026-08-05',
    executionStarted: true,
    executionStartDate: '2026-07-10',
    actualFinishedDate: null,
    toBeApprovedByManagement: true,
    submittedForApprovalAt: '2026-07-28T09:15:00.000Z',
    approvalDate: null,
    remarks: 'Awaiting final sign-off from Management before publishing collateral.',
    budget: 15000,
    actualSpend: 14200,
    subtasks: [
      { id: 'st-201', title: 'Executive Outline & Speaker Notes', completed: true },
      { id: 'st-202', title: 'Custom 4K Motion Slides', completed: true },
      { id: 'st-203', title: 'Teaser Video Sound Sync', completed: true }
    ],
    comments: [
      { id: 'c-201', author: 'Priya Verma', role: 'Marketing Team', text: 'Submitted package for final Management approval.', timestamp: '2026-07-29T10:15:00Z' }
    ],
    isOverdue: false,
    createdAt: '2026-07-10T11:00:00Z',
    updatedAt: '2026-07-29T10:15:00Z',
  },
  {
    id: 'TSK-1003',
    project: 'SEO & Content Overhaul',
    taskName: 'Q3 Pillar Blog Posts & Whitepaper Design',
    taskBrief: 'Write 5 technical pillar guides and design downloadable PDF eBooks for lead generation.',
    department: 'Content & PR',
    internalPoc: 'Rohan Mehta',
    agency: 'Echo PR Studio',
    vendor: 'PrintCraft Solutions',
    priority: 'Medium',
    taskProgress: 'In Progress',
    deadline: '2026-08-15',
    executionStarted: true,
    executionStartDate: '2026-07-18',
    actualFinishedDate: null,
    toBeApprovedByManagement: false,
    submittedForApprovalAt: null,
    approvalDate: null,
    remarks: '3 out of 5 articles drafted. PDF layout template ready.',
    budget: 8000,
    actualSpend: 4500,
    subtasks: [
      { id: 'st-301', title: 'Pillar Articles 1-3 Writing', completed: true },
      { id: 'st-302', title: 'Pillar Articles 4-5 Writing', completed: false },
      { id: 'st-303', title: 'PDF Layout Design', completed: true }
    ],
    isOverdue: false,
    createdAt: '2026-07-18T08:00:00Z',
    updatedAt: '2026-07-27T16:45:00Z',
  },
  {
    id: 'TSK-1004',
    project: 'Annual Customer Conference 2026',
    taskName: 'Sponsor Booth Signage & Swag Production',
    taskBrief: 'Print custom fabric backdrops, acrylic signs, and eco-friendly swag boxes for attendees.',
    department: 'Event Marketing',
    internalPoc: 'Karan Patel',
    agency: 'Apex Creative Studio',
    vendor: 'PrintCraft Solutions',
    priority: 'Urgent',
    taskProgress: 'Overdue' as TaskStatus,
    deadline: '2026-07-25',
    executionStarted: true,
    executionStartDate: '2026-07-02',
    actualFinishedDate: null,
    toBeApprovedByManagement: false,
    submittedForApprovalAt: null,
    approvalDate: null,
    remarks: 'Vendor shipment delayed by 3 days. Urgently tracking delivery.',
    budget: 30000,
    actualSpend: 31500,
    subtasks: [
      { id: 'st-401', title: 'Vector Artwork Final Approval', completed: true },
      { id: 'st-402', title: 'Fabric Banner Printing', completed: true },
      { id: 'st-403', title: 'Eco Swag Box Assembly & Shipping', completed: false }
    ],
    isOverdue: true,
    createdAt: '2026-07-02T10:00:00Z',
    updatedAt: '2026-07-26T09:00:00Z',
  },
  {
    id: 'TSK-1005',
    project: 'Social Media Growth Hacking',
    taskName: 'July Reel & TikTok Series (20 Videos)',
    taskBrief: 'Film and edit 20 short-form educational videos highlighting product features.',
    department: 'Brand & Creative',
    internalPoc: 'Aarav Sharma',
    agency: 'Apex Media Global',
    vendor: 'PixelPerfect Visuals',
    priority: 'Medium',
    taskProgress: 'Completed',
    deadline: '2026-07-28',
    executionStarted: true,
    executionStartDate: '2026-07-01',
    actualFinishedDate: '2026-07-27',
    toBeApprovedByManagement: false,
    submittedForApprovalAt: null,
    approvalDate: '2026-07-27',
    remarks: 'All 20 videos scheduled on Buffer. Average engagement up 40%.',
    budget: 12000,
    actualSpend: 11000,
    subtasks: [
      { id: 'st-501', title: 'Video Concepts & Captions', completed: true },
      { id: 'st-502', title: 'Shooting Day 1 & 2', completed: true },
      { id: 'st-503', title: 'Color Grading & Subtitle Editing', completed: true }
    ],
    isOverdue: false,
    createdAt: '2026-07-01T14:00:00Z',
    updatedAt: '2026-07-27T18:00:00Z',
  },
  {
    id: 'TSK-1006',
    project: 'Q3 Brand Awareness Campaign',
    taskName: 'Meta & LinkedIn Paid Ads Setup',
    taskBrief: 'Configure ad accounts, pixel tracking, audience retargeting, and creative variations.',
    department: 'Performance Marketing',
    internalPoc: 'Priya Verma',
    agency: 'Apex Media Global',
    vendor: 'CloudScale Hosting',
    priority: 'High',
    taskProgress: 'To Be Approved by Management',
    deadline: '2026-08-02',
    executionStarted: true,
    executionStartDate: '2026-07-20',
    actualFinishedDate: null,
    toBeApprovedByManagement: true,
    submittedForApprovalAt: '2026-07-28T09:15:00.000Z',
    approvalDate: null,
    remarks: 'Ad copy and $50k budget allocation pending Management approval.',
    budget: 50000,
    actualSpend: 50000,
    isOverdue: false,
    createdAt: '2026-07-20T13:00:00Z',
    updatedAt: '2026-07-29T11:30:00Z',
  },
  {
    id: 'TSK-1007',
    project: 'Product Launch v4.0',
    taskName: 'Customer Case Study Video Series',
    taskBrief: 'Interview 3 enterprise customers and edit 3-minute success story videos.',
    department: 'Product Marketing',
    internalPoc: 'Rohan Mehta',
    agency: 'Echo PR Studio',
    vendor: 'OmniStream Video',
    priority: 'Low',
    taskProgress: 'Not Started',
    deadline: '2026-08-25',
    executionStarted: false,
    executionStartDate: null,
    actualFinishedDate: null,
    toBeApprovedByManagement: false,
    submittedForApprovalAt: null,
    approvalDate: null,
    remarks: 'Customer consent forms sent out.',
    budget: 18000,
    actualSpend: 0,
    isOverdue: false,
    createdAt: '2026-07-22T15:00:00Z',
    updatedAt: '2026-07-22T15:00:00Z',
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    user: 'Management Admin',
    role: 'Admin',
    date: '2026-07-29',
    time: '11:30:12',
    action: 'Approval Requested',
    target: 'TSK-1006',
    oldValue: 'In Progress',
    newValue: 'To Be Approved by Management',
  },
  {
    id: 'log-2',
    user: 'Priya Verma',
    role: 'Marketing Team',
    date: '2026-07-29',
    time: '10:15:44',
    action: 'Status Updated',
    target: 'TSK-1002',
    oldValue: 'In Progress',
    newValue: 'To Be Approved by Management',
  },
  {
    id: 'log-3',
    user: 'Aarav Sharma',
    role: 'Marketing Team',
    date: '2026-07-27',
    time: '18:00:00',
    action: 'Task Completed',
    target: 'TSK-1005',
    oldValue: 'In Progress',
    newValue: 'Completed',
  },
  {
    id: 'log-4',
    user: 'System Automation',
    role: 'Admin',
    date: '2026-07-26',
    time: '00:01:00',
    action: 'Overdue Triggered',
    target: 'TSK-1004',
    oldValue: 'In Progress',
    newValue: 'Overdue (Highlight Red)',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Management Approval Pending',
    message: 'Task "GTM Keynote Deck & Launch Video Package" requires your approval.',
    type: 'approval_request',
    timestamp: '2026-07-29T10:15:00Z',
    read: false,
    taskId: 'TSK-1002'
  },
  {
    id: 'notif-2',
    title: 'Task Overdue Warning',
    message: 'Task "Sponsor Booth Signage & Swag Production" passed deadline (2026-07-25).',
    type: 'overdue',
    timestamp: '2026-07-26T00:01:00Z',
    read: false,
    taskId: 'TSK-1004'
  },
  {
    id: 'notif-3',
    title: 'Task Completed',
    message: 'Aarav Sharma completed "July Reel & TikTok Series (20 Videos)".',
    type: 'completed',
    timestamp: '2026-07-27T18:00:00Z',
    read: true,
    taskId: 'TSK-1005'
  }
];
